sonar.organization=mrrobertkent
sonar.projectKey=mrrobertkent_hookgate
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=dist/**,**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
